### ISSUE TITLE
Use official PWA module for implementation

### ISSUE THREAD

**Issue by TheAlexLichter** [gerardofelipe/ecommerce-netlify-pwa#3]
Hey 👋 

I'd suggest to implement the service worker features via [the official PWA module](https://pwa.nuxtjs.org/modules/workbox.html) which would lead to less boilerplate and a nice "real life" example for the module as well

**Comment by gerardofelipe** [comment]
Hey @manniL thanks for your feedback!

I wanted to explain two different approaches, using the @nuxtjs/pwa module and using Google's Workbox Libraries.

The first one is great and, as you said, that's probably what you would use in "real life" Nuxtjs project, but it's too linked to the framework, so I miss some parts of Workbox that I want to show and that's why I've also used the other approach.

The idea is to show the development process using the different branches, to get an idea of the why and how of some decisions and the different ways of doing things. Anyway, I'm still making improvements to the repository. 

**The last big update:**

- Improvements in the branches "@nuxtjs/pwa" to get the same functionality as injectManifest and added OneSignal push notifications.

- I moved those enhancements to master and published it to the Netlify page. You can see the improvements there and I hope you like them.

- As I see that you are more interested in the @nuxtjs/pwa part, I have updated the Readme file with the order to follow the branches.

Cheers

**Comment by TheAlexLichter** [comment]
Hey @gerardofelipe 

Thanks for the effort! :relaxed:
